version: "3"
services:
  application:
    image: spring-boot-mysql
    ports:
      - "9090:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql
    networks:
      - springboot-db-net
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=product
    - MYSQL_USER=root  
  
    volumes:
      - /data/mysql
networks:
  springboot-db-net: