version: "3"
services:
  application:
    image: spring-boot-image
    ports:
      - "9090:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://3.109.133.146:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
      - /data/springboot-app:/path/in/container
